### PR TITLE
Move WithMetadata with mapping for OpenGenericAssemblyScanning

### PR DESCRIPTION
**Pull request by romerod**
Add support for adding metadata accepting a type to metadata mapper.

### CODE REVIEW

**Comment by tillig** [comment]
I think this looks good. I'm not sure why it was internal to start - we have a test for it to verify it works, but it was working due to access to internals. Before I approve - @alistairjevans @RaymondHuy do you guys know if there was a specific reason this was internal or was it just an oversight?

**Comment by alistairjevans** [comment]
Looks like it was just an oversight; the tests for it clearly believe it to be publicly accessible. @romerod, can you also move the `WithMetadataFrom` method below it, which I suspect fell foul of the same problem?

**Comment by RaymondHuy** [comment]
@tillig  yes, it's my mistake, I'm sorry about it.

**Comment by romerod** [comment]
OK, i'll move the other method on monday.

Thanks for the review.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Review by tillig — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
