### PR TITLE
reduce lock contention in LifetimeScope.CreateSharedInstance

### PR DESCRIPTION
**Pull request by botinko**
image

Found lock contention while load testing of our application. Avoid locking on happy path.

### CODE REVIEW

**Review by tillig — APPROVED** [review]
LGTM! Thanks for this, I love little optimizing PRs that make things better for everyone.

**Comment by botinko** [comment]
@tillig Sure! When can we expect a new release? Can I at least make a developer build for [MyGet](https://www.myget.org/feed/autofac/package/nuget/Autofac)? There are no new build since 7.0.0 release. 
In our load tests, the problem is reproducible. Or I can create the package by myself and put it in private repo.

**Comment by tillig** [comment]
All develop builds are already in MyGet, but they'll show as _earlier_ than 7.0 because we haven't incremented the version. Look at the date instead. I've been a bit busy trying to get compatibility releases out for Autofac 7 integration packages, sorry.

**Comment by botinko** [comment]
Thanks! [7.0.0-develop-01517](https://www.myget.org/feed/autofac/package/nuget/Autofac/7.0.0-develop-01517) build works for me.

**Comment by tillig** [comment]
I'm working hard on getting a 7.0.1 out and it should be out soon but MyGet is having some problems right now where I push a package but it isn't showing up in the feed. I'm working with MyGet now on that. _Eventually_ (and soon) you should see a 7.0.1 on NuGet proper.

**Pull request merged**
