### PR TITLE
feat: build using Ubuntu image

### PR DESCRIPTION
**Pull request by alsami**
* Update `appveyor.yml` to use Ubuntu image and re-order some stuff a bit
* Do not install dotnet-sdk manually on linux

### CODE REVIEW

**Comment by alsami** [comment]
@tillig @alistairjevans 

Just tried it out a bit, some stuff breaks because of case-sensitivity now (Build vs build for instance).
Also I see some stuff is redundant and can be simplified when using bash instead of powershell. 

You guys want to continue using powershell or would bash be okay?

**Comment by tillig** [comment]
I think leaving the build as PowerShell has a couple of benefits: it can be used on both Windows or Mac/Linux (PowerShell Core); and we'll still be able to share some of the build script bits with the other builds which may not be entirely Linux-buildable, like the WCF or MVC extensions.

**Comment by alsami** [comment]
Okay great. I really love being able to edit this solution now without the need to put up a virtual machine!

Build should be fine, so ready for review

**Comment by alsami** [comment]
It's actually slower than building on windows. The last successful build on windows took 2min and 40secs, whereas the Ubuntu build took 2min and 57secs.

**Pull request merged**
