### PR TITLE
feat: remove interface for IResolveRequestContext

### PR DESCRIPTION
**Pull request by alsami**
Part of #1164, bringing back performance improvements

* Rename `ResolveRequestContext` to `DefaultResolveRequestContext`
* Rename `ResolveRequestContextBase` to `ResolveRequestContext`
* Rename `MockResolveRequestContext` to `ResolveRequestContextStub`
* Rename `MockLifetimeScope` to `LifetimeScopeStub`
* Implement minimum requirements in tests for `ResolveRequestContextSub`

### CODE REVIEW

**Comment by alsami** [comment]
@alistairjevans as discussed in #1174, this brings base `ResolveRequestContextBase`, defining all methods as abstract.

Mind running benchmarks again?

**Comment by alsami** [comment]
|  DeepGraphResolveBenchmark |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------- |---------:|---------:|---------:|-------:|------:|------:|----------:|
| PR | 20.40 us | 0.174 us | 0.136 us | 0.5798 |     - |     - |  19.49 KB |
| Resolve | 20.47 us | 0.075 us | 0.070 us | 0.5798 |     - |     - |  19.49 KB |

This is what I got on Linux, a tiny bit better. Can't test develop though.

**Comment by alistairjevans** [comment]
I got the same thing basically:

|  Method |     Mean |    Error |   StdDev |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|-------- |---------:|---------:|---------:|-------:|-------:|------:|----------:|
| v6 (before any refactoring) | 10.54 us | 0.053 us | 0.047 us | 2.0599 | 0.0458 |     - |  16.91 KB |
| 1174 | 11.50 us | 0.064 us | 0.057 us | 2.3804 | 0.0610 |     - |  19.49 KB |
| PR | 11.22 us | 0.033 us | 0.029 us | 2.3804 | 0.0610 |     - |  19.49 KB |

The red flag for me though is the fact that the original refactoring seems to have jumped the memory allocations loads...

**Comment by alsami** [comment]
It's still 0.3 us slower than v6 before refactoring as well. Maybe it's also the type casting for the interface?
The memory allocation I don't understand tbh. What has changed that should consume more memory? :thinking:

**Comment by alistairjevans** [comment]
Ok, just trying to narrow this down some more:

|  Method |     Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|-------- |---------:|----------:|----------:|-------:|-------:|------:|----------:|
| v6 pre-1173 | 9.603 us | 0.0813 us | 0.0721 us | 2.0599 | 0.0458 |     - |  16.91 KB |
| v6 post-1173 | 10.59 us | 0.075 us | 0.067 us | 2.0599 | 0.0458 |     - |  16.91 KB |
| v6 post-1174 |  11.23 us | 0.038 us | 0.032 us | 2.3804 | 0.0610 |     - |  19.49 KB |
| PR | 11.03 us | 0.045 us | 0.040 us | 2.3804 | 0.0610 |     - |  19.49 KB |

So, 1174 started consuming a lot more memory. Curious.

**Comment by alistairjevans** [comment]
I think I might have found the memory issue; you changed the ConcurrencyMiddleware to use .Any:

image

That's going to allocate an Action instance every time we hit the loop, plus the overhead of the Any LINQ construct itself.

As a rule I'm trying to strip out any LINQ from the hot-path areas because it adds overhead.

**Comment by alsami** [comment]
Makes sense, give me a second, changing it back to not use LINQ.

**Comment by alsami** [comment]
Back to original memory-usage.

|  DeepGraphResolveBenchmark |     Mean |    Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------- |---------:|---------:|---------:|-------:|------:|------:|----------:|
| PR | 18.12 us | 0.056 us | 0.044 us | 0.4883 |     - |     - |  16.91 KB |
| v6 (latest) | 19.78 us | 0.097 us | 0.091 us | 0.5798 |     - |     - |  19.49 KB |

Is the small diff in perf acceptable?

**Comment by alistairjevans** [comment]
Yeah, when you pass a lambda to a method, and that lambda captures a local variable, it allocates a new instance of an object to hold that capture+delegate. It's sneaky, but shows up under a decompiler.

I'll run those diff-ing benchmarks again tomorrow, then we can see what else (if anything) might need changing to bring that perf back up.

**Comment by alsami** [comment]
| Method | Mean | Error | StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------- |---------:|---------:|---------:|-------:|------:|------:|----------:|
| Resolve | 20.12 us | 0.118 us | 0.105 us | 0.5798 | - | - | 19.49 KB |

> I'll run those diff-ing benchmarks again tomorrow, then we can see what else (if anything) might need changing to bring that perf back up.

Sounds good!

**Comment by alsami** [comment]
test

**Comment by alsami** [comment]
hello

**Comment by alsami** [comment]
ddsadsadsadsad

**Comment by alsami** [comment]
sdasd

**Comment by alsami** [comment]
sadasdsad

**Comment by alsami** [comment]
s

**Comment by alsami** [comment]
s

**Comment by alsami** [comment]
autobot benchmark RootContainerResolveBenchmark develop v6

**Comment by alsami** [comment]
autobot benchmark RootContainerResolveBenchmark develop v6

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark commit:d13dfd6b978de6bbb8870e58af76a092b54f2408 feat/bring_back_base_resolverequestcontext

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6 feat/bring_back_base_resolverequestcontext

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6

**Comment by alsami** [comment]
src\Autofac.Benchmark.Api\Controllers\BenchmarksController.cs : 27

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@alistairjevans sorry for cluttering the PR, please feel free to delete the comments.

If you want to run benchmarks, you can do so now automated.

Checkout the help of the bot by typing `autobot help`

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot help

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6 feat/bring_back_base_resolverequestcontext

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6 feat/bring_back_base_resolverequestcontext

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop feat/bring_back_base_resolverequestcontext

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark v6 feat/bring_back_base_resolverequestcontext

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop feat/bring_back_base_resolverequestcontext

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop feat/bring_back_base_resolverequestcontext

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop feat/bring_back_base_resolverequestcontext

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop feat/bring_back_base_resolverequestcontext

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark develop

**Comment by alsami** [comment]
autobot benchmark DeepGraphResolveBenchmark

**Comment by alistairjevans** [comment]
Ran the benchmarks again (manually):

|  Method |     Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|-------- |---------:|----------:|----------:|-------:|-------:|------:|----------:|
| v6 pre-1173 | 9.486 us | 0.0497 us | 0.0464 us | 2.0599 | 0.0458 |     - |  16.91 KB |
| v6 post-1173 | 10.51 us | 0.042 us | 0.040 us | 2.0599 | 0.0458 |     - |  16.91 KB |
| v6 post-1174 | 11.31 us | 0.101 us | 0.094 us | 2.3804 | 0.0610 |     - |  19.49 KB |
| PR | 10.50 us | 0.052 us | 0.049 us | 2.0599 | 0.0458 |     - |  16.91 KB |

So, the memory issue has been fixed, and we're back to the fact that #1173 introduced the main slow down. #1173 change the resolve context to an interface, but we've just changed it back...very strange. I'll take another look at #1173.

**Comment by alsami** [comment]
If you check out the diff between #1173 and #1174, you will see that there was an increase in time as well. #1174.

I'd try to check if it's related to the interface casting. Interface casting can be a bit more costly AFAIK. The diff here is 1µs, this could be really it.

**Comment by alistairjevans** [comment]
The 1173 to 1174 drop in perf were due to the additional memory allocation; the changes in this PR bring that perf back down to post-1173 levels.

We've not taken `ResolveRequestContext` back to being a class, so unless I'm missing something, something in 1173, besides the change to interfaces, caused a performance problem.

One thing I've noticed is that you unsealed `ResolveRequestContext` in those changes; can you try putting that back? Sealed classes can sometimes perform better than unsealed ones.

**Comment by alsami** [comment]
> One thing I've noticed is that you unsealed `ResolveRequestContext` in those changes; can you try putting that back? Sealed classes can sometimes perform better than unsealed ones.

Will look into it tonight, since there is the class `MockPipelineRequestContext`, which derived previously from `ResolveRequestContextBase`. Now that `ResolveRequestContextBase` is all abstract, that's not an easy change.

**Comment by alistairjevans** [comment]
Actually, I've also realised that **all** of the properties in `ResolveRequestContextBase` are now virtual (because they're abstract), meaning they will employ a similar vtable lookup to an interface. Before, most of the properties in the `ResolveRequestContextBase` were not virtual, so they would have been faster.

That virtual property access may be what's killing us.

It may come down to changing the ResolveRequestContextBase back to taking constructor parameters.

**Comment by alsami** [comment]
> It may come down to changing the ResolveRequestContextBase back to taking constructor parameters.

Ah, jeez. Will give it a shot later and run the benchmarks again locally. Let's see if that's the cause. If so, we need something that's more testable. 

Basically that would mean multi-inheritance, something like
`DefaultResolveRequestContext` -> `ResolveRequestContextBase` -> `ResolveRequestContext`.

**Comment by tillig** [comment]
I admit I'm only sorta following all this. With the other reviews and such going on, I haven't had the ability to dive in and think I'd just be a distraction. The ultimate goal of having testable extensions stands.

On that note, I'm holding on the DOT graph thing until this settles out. It's not a rush; I'd rather get it right than get it fast. But I don't see the value in updating it on each of these changes until we're happy with them.

**Comment by alsami** [comment]
> But I don't see the value in updating it on each of these changes until we're happy with them.

You mean you would make all of the changes requested in #1164 with a single PR?

**Comment by alistairjevans** [comment]
I believe @tillig is just referring to the remaining work on the DOT graph support. No point finishing it until the structures have stabilised.

**Comment by alistairjevans** [comment]
Shamelessly looking at the [HttpContext](https://github.com/dotnet/aspnetcore/blob/master/src/Http/Http.Abstractions/src/HttpContext.cs) code in the dotnet runtime, that is an abstract class with all the properties abstract.

The [DefaultHttpContext](https://github.com/dotnet/aspnetcore/blob/master/src/Http/Http/src/DefaultHttpContext.cs) is then a sealed class on top of that.

Part of me thinks that if it's good enough for the .NET Core team, we should probably embrace the same pattern, as @alsami mostly already has in the changes so far. If there was a better way, they would probably have already done it.

So I'm now settling on the abstract class as we currently have, but perhaps let's do a rename to be a similar pattern to the HttpContext style, with the base class just called `ResolveRequestContext`, and then a `DefaultResolveRequestContext` implementation (that's sealed).  Tests can implement/mock `ResolveRequestContext` as they see fit.

**Comment by tillig** [comment]
> just referring to the remaining work on the DOT graph support. No point finishing it until the structures have stabilised.

Yup, that. I'm in no rush and don't want to pressure anyone. Just saying I'll wait so I can avoid the thrashing.

> Shamelessly looking at the HttpContext code in the dotnet runtime, that is an abstract class with all the properties abstract.

When I originally filed #1164 that was definitely one of the first things I was thinking about, mostly because I'd seen reasonable testing success that way and, admittedly, most of my work _at work_ is ASP.NET Core so it was top of mind. I'd be totally fine with that pattern.

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark develop

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark commit:d13dfd6b978de6bbb8870e58af76a092b54f2408

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@alistairjevans sorry again for bloating the PR with random messages. Please delete all of them until the last valid from @tillig.

**Comment by alsami** [comment]
> So I'm now settling on the abstract class as we currently have, but perhaps let's do a rename to be a similar pattern to the HttpContext style, with the base class just called `ResolveRequestContext`, and then a `DefaultResolveRequestContext` implementation (that's sealed). Tests can implement/mock `ResolveRequestContext` as they see fit.

So basically the following steps left to do:
-  Rename `ResolveRequestContext` to `DefaultResolveRequestContext` and seal it
-  Rename `ResolveRequestContextBase` to `ResolveRequestContext`
-  Create class `TestableResolveRequestContext` ?! and make it derive from `ResolveRequestContext` just for testing purposes

Just making sure that I've understood you correctly.

**Comment by alistairjevans** [comment]
Pretty much, yeah.

**Comment by alistairjevans** [comment]
Any 'Testable' classes would go into the test projects though. Or we just use Moq, which has recently been added to the project.

**Comment by alsami** [comment]
@alistairjevans I've applied the changes as we have agreed on.

Very interesting is that the test `RepeatedResolveWhileTheScopeIsDisposing_ObjectDisposedExceptionThrownOnly`, has failed for the past two pipeline. [Here](RepeatedResolveWhileTheScopeIsDisposing_ObjectDisposedExceptionThrownOnly) and [here](https://github.com/autofac/Autofac/pull/1176). I've executed it locally many times, can't get it to fail.

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark

**Comment by alsami** [comment]
Benchmarks looking good.

**Comment by alsami** [comment]
@autofac-bot benchmark DeepGraphResolveBenchmark commit:944d4cb4b6b630f70229daf9de7726d5a3dbe848

**Comment by alsami** [comment]
Test run [number3](https://ci.appveyor.com/project/Autofac/autofac/builds/34456531) magically passed 🤷‍♂️

**Comment by alistairjevans** [comment]
Great, I love intermittent errors that only happen in CI. /s

Looks like somethings not right with the benchmarks, look like an exception is getting output?

Is there a way to indicate to the bot that we only want the results rather than the full output?

**Comment by alsami** [comment]
> Looks like somethings not right with the benchmarks, look like an exception is getting output?

Yeah, it's because I am publishing the benchmarks before executing them. That only works when changes from #1181 are applied. In that specific commit, that's not the case.



> Is there a way to indicate to the bot that we only want the results rather than the full output?

In this case you mean that you don't want to show the exception, but only the valid results, if they are present? If so, I could change the code to hide the exception details.

**Comment by tillig** [comment]
You can use some fancy XML tags to have collapsible bits if you want.

```html
<details>
<summary>Collapsible panel!</summary>
This is the detail that is hidden by the panel.
</details>
```

That renders as:

<details>
<summary>Collapsible panel!</summary>
This is the detail that is hidden by the panel.
</details>

I don't think it makes the emails shorter, but the rendered view gets tidier.

**Comment by alsami** [comment]
Will do, doing so also for the complete output. Will just hide the error instead!

**Comment by alistairjevans** [comment]
90% of the time all we'll care about is the summary table from each benchmark. The full verbose output makes it harder to compare.

Any way to only print the result table of each unless we explicitly ask for it to be more verbose?

**Comment by alsami** [comment]
> Any way to only print the result table of each unless we explicitly ask for it to be more verbose?

You want the full output in the collapse only if requested?

**Comment by alistairjevans** [comment]
Could do, but I'd also be happy with a `/verbose` option on the original command.

Basically, I'm not too fussed about the exact format, provided the two result tables are visually adjacent when viewed in GitHub.

**Comment by alsami** [comment]
Sure, can do so, hopefully the upcoming weekend.

**Comment by alistairjevans** [comment]
Cool, thanks. 😀

I'll take a look at the updates to this PR tomorrow and get it merged in.

**Comment by alsami** [comment]
> Could do, but I'd also be happy with a `/verbose` option on the original command.
> 
> Basically, I'm not too fussed about the exact format, provided the two result tables are visually adjacent when viewed in GitHub.

@tillig would be great if you could clone and add the repositories to the org, so that we can collect issues/feature requests there

**Comment by tillig** [comment]
Yup, I'm a little under the gun at work so this isn't going to happen today.

**Comment by alsami** [comment]
No worries, tyt.

**Pull request merged**
