### PR TITLE
chore: update coverlage packages to stable 3.0.0 version

### PR DESCRIPTION
**Pull request by alsami**
As per #1241, updating coverlet* to stable 3.0.0 release.

### CODE REVIEW

**Review by tillig — APPROVED** [review]
💯

**Comment by alistairjevans** [comment]
Thanks for staying on top of this @alsami!

**Comment by alistairjevans** [comment]
I actually just noticed that our coverage dropped by 14% according to that latest coverage report. Any idea what's up with that? Is it due to the new version?

**Comment by alsami** [comment]
Yes, I noticed that too, damn, should have marked it as WIP. Will find a solution soon.

**Comment by alistairjevans** [comment]
Just linking https://github.com/autofac/Autofac/pull/1246 for cross-referencing coverage issues.

**Pull request merged**
