### PR TITLE
Minor NRT corrections for test files

### PR DESCRIPTION
**Pull request by alistairjevans**
Not sure why the NRT warnings aren't failing the build, but I've fixed the issue.

### CODE REVIEW

**Comment by alistairjevans** [comment]
Aaargghhhhh!!! The build failed on that CI problem that I've failed to replicate all of yesterday!!! Sob.

**Comment by tillig** [comment]
Before merging... it looks like the code coverage thing changed and is failing the check. I wonder if we need to tweak that; I don't see that we can fix coverage on nullable markup any more than we could affect coverage when adding an `async`/`await` operation where the compiler generates that whole async wait state machine thing. I've been hit by that before, too - can't cover that stupid async/await thing but the lines of code themselves are covered.

**Comment by alistairjevans** [comment]
Is that a setting in CodeCov for a tolerance threshold, or is it a setting when we run the build? @alsami?

**Comment by alistairjevans** [comment]
I'm going to merge this in spite of the codecov problem because it's blocking the merge to develop.

**Comment by alsami** [comment]
> Is that a setting in CodeCov for a tolerance threshold, or is it a setting when we run the build? @alsami?

I will look into it. If it's possible, what threshold would you think is acceptable? 1%? 2%? We could also decide to not let the checks fail, when the coverage lowered.

**Comment by alistairjevans** [comment]
1% might be enough for now to ignore minute fluctuations? 

Not sure, may be a case of trial and error.

**Pull request merged**
