### PR TITLE
Provide the instance type being property injected onto via NamedParameter

### PR DESCRIPTION
**Pull request by sheastrickland**
Moved here via suggestion from @tillig in PR #643 

//cc @nblumhardt

### CODE REVIEW

**Comment by alexmg** [comment]
I have merged this but it isn't sitting quite right with me at the moment.

Can you post an example of using this property with Serilog so that we can think about some other approaches?

How does your objective line up with the sample below?

http://docs.autofac.org/en/latest/examples/log4net.html

**Comment by sheastrickland** [comment]
Thanks @alexmg, the main objective is injecting properties on an existing instance. The particular case where this arose, was using the `Autofac.Web` package and utilising the Http Modules which perform property injection on existing UserControls and Page instances. 

The log4net examples all work when the property is injected while constructing the instance containing the property to inject, however; when an existing instance of the containing type is injected onto after, it doesn't fire the Activated event.

The Http Modules call [ResolutionExtensions.InjectProperties](https://github.com/autofac/Autofac/blob/master/src/Autofac/ResolutionExtensions.cs#L51). Which proxies down to [AutowiringPropertyInjector.InjectProperties](https://github.com/autofac/Autofac/blob/master/src/Autofac/Core/Activators/Reflection/AutowiringPropertyInjector.cs#L60), so unless the TLogger is registered in the container it will short circuit here.

So, after registering the TLogger factory, which will pass the previous short circuit, when it gets to the [Resolve](https://github.com/autofac/Autofac/blob/master/src/Autofac/Core/Activators/Reflection/AutowiringPropertyInjector.cs#L71), it's missing the instanceType context.

Enter the `NamedParameter` :)

It's hard to articulate, though in short: Injecting onto an existing type with `InjectProperties` and it's kin. Doesn't provide the same hooks as what `AttachToComponentRegistration` and `IComponentRegistration` provide.

**Comment by sheastrickland** [comment]
So, similar to PR #644, we have this:

https://gist.github.com/sheastrickland/e2899cd7abe61e20de69

With the additional hooks for PropertyInjection when the containing type is resolved, as well as when an existing instance it property injected onto, after the fact.

**Comment by piers7** [comment]
Nitpicking, but shouldn't InstanceTypeNamedParameter be `public static readonly`, not `public const`, to avoid binary versioning issues if you ever change the magic string?

**Comment by piers7** [comment]
So now I want to achieve the same as @sheastrickland I had a bit of a poke around, and now finally understand (and generally concur with) the summary above.

I think the root cause here is there just aren't the same hooks for controlling Property injection that exist for Parameters. Were it possible to extend a component's _Properties_ during Preparing/Activating (just as you can currently extend their Parameters) then we wouldn't need to do this - a log injection module could just add that dependency explicitly.

The approach used in the log4net doco sample waits until after the component has been Activated, then re-does half of the work that the activator has just done (scanning the properties, matching by type, checking it's not alread set). I'm currently using that approach, but I've not had to deal with @sheastrickland's issue with Activated not firing in some cases. Eitherway, it feels like a workaround to something that's missing.

Another potential option would be if the property injection engine (the InjectUnsetProperties) method were itself to be able to be re-used here, by explicitly passing parameters (or object instances) to it, and it auto-injecting the residual. Can't say I fancy that much, seems like too big a change.

I can't say I massively like the magic-string-named-parameter, but it does seem to me to be a neat, discrete fix for something that otherwise needs a fair bit of effort to unravel.

**Pull request merged**
