### PR TITLE
Resolved localization failure reported in issue #597

### PR DESCRIPTION
**Pull request by claudiobernasconi**
<b>Introduction:</b>
I'm trying to start contributing to Autofac and grabed the simplest issue first to get everything setup on my machine. So please feel free to suggest anything I maybe do the wrong way.

<b>Fixed Issue:</b>
As reported in the original issue #597 a single unit test fails executing on a machine with different localization than English. I implemented and tested the code provided by @MircoBabin. As a result all of the non-ignored unit tests run successfully on a localized machine.

### CODE REVIEW

**Comment by claudiobernasconi** [comment]
Can anyone help me with the failing AppVeyor feedback? I do not understand the error message.
<pre>Specify which project or solution file to use because the folder contains more than one project or solution file.</pre>
Thank you.

**Comment by alexmg** [comment]
Hi @claudiobernasconi. Thanks for helping out. We are in the middle of splitting out the integrations and extras into separate repositories and have been testing AppVeyor for builds (it looks good). I created an Autofac project on AppVeyor as a place holder to ensure the main project got the correct URL. I didn't disable the build on PR setting so it triggered a build, and given that nothing has been configured yet, the build didn't go so well. Nothing to worry about. :smile:

**Comment by alexmg** [comment]
The build was fine BTW. :ok_hand:

**Comment by claudiobernasconi** [comment]
Thanks for your feedback. The issue https://github.com/autofac/Autofac/issues/597 can be closed in my opinion. What do you think?

**Pull request merged**
